### PR TITLE
Chore: Upgrade Angular

### LINKED ISSUE #192: chore: upgrade angular
**Description**

Angular should be updated to 18

### PR DESCRIPTION
**Pull request by sorenjohanson**
closes #192

### CODE REVIEW

**Comment by JannikStreek** [comment]
```
Unknown error: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/node/app/node_modules/wrap-ansi/index.js from /home/node/app/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /home/node/app/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

When I run `yarn start`. Don't you have that issue?

**Comment by JannikStreek** [comment]
@sorenjohanson can you fix the conflicts and fix the build errors so we can merge this?

**Comment by sorenjohanson** [comment]
Done, though idk if the tests will fail again as they seem to be getting the cli error (even though I can't reproduce it locally anymore)

**Comment by JannikStreek** [comment]
what's the status here?

**Comment by sorenjohanson** [comment]
Can you still get the cli error to reproduce when checking out? I can't, so I have no idea why yarn lint and test are failing.

**Comment by JannikStreek** [comment]
Fixed with https://github.com/kitsteam/stop-motion-app/pull/249, closing

**Pull request closed without merging**
